# Generated by Django 3.1.7 on 2021-07-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=100)),
                ('img', models.ImageField(default='null', upload_to='ArtiguloIMG')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreA', models.CharField(max_length=100)),
                ('precioA', models.CharField(max_length=100)),
                ('imgA', models.ImageField(default='null', upload_to='ArtiguloIMG')),
            ],
        ),
    ]
